name: Docker Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
        uses: docker/build-push-action@v1.1.1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: cryptic-ai
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.GITHUB_TOKEN }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: docker.pkg.github.com
          # Docker repository to tag the image with
          repository: glosharp/hooksharp
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest, v$MAJOR.$MINOR.$BUILD
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          dockerfile: Hooksharp/Dockerfile
          # Comma-delimited list of labels to add to the built image
          labels: |
            org.maintainers=glosharp
            org.maintainers.support=github
            org.maintainers.site=glosharp.com
          # Adds labels with git repository information to the built image
          add_git_labels: true
          # Whether to push the image
          push: true
        env:
          MAJOR: 1
          MINOR: 0
          BUILD: $GITHUB_RUN_NUMBER
