name: Hooksharp Deploy

on:
  push: [ master ]

jobs:
  Hooksharp-API-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish
        run: |
          dotnet publish --configuration Release --self-contained true --runtime linux-x64 --output /releases/linux
          dotnet publish --configuration Release --self-contained true --runtime win-x64 --output /releases/windows
      - name: Create release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: >
            /releases/linux
            /releases/windows
            
